# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/server203/msm8909/libvncserver-LibVNCServer-0.9.11

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/server203/msm8909/libvncserver-LibVNCServer-0.9.11

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/server203/msm8909/libvncserver-LibVNCServer-0.9.11/CMakeFiles /home/server203/msm8909/libvncserver-LibVNCServer-0.9.11/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/server203/msm8909/libvncserver-LibVNCServer-0.9.11/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named client_examples_SDLvncviewer

# Build rule for target.
client_examples_SDLvncviewer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 client_examples_SDLvncviewer
.PHONY : client_examples_SDLvncviewer

# fast build rule for target.
client_examples_SDLvncviewer/fast:
	$(MAKE) -f CMakeFiles/client_examples_SDLvncviewer.dir/build.make CMakeFiles/client_examples_SDLvncviewer.dir/build
.PHONY : client_examples_SDLvncviewer/fast

#=============================================================================
# Target rules for targets named client_examples_backchannel

# Build rule for target.
client_examples_backchannel: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 client_examples_backchannel
.PHONY : client_examples_backchannel

# fast build rule for target.
client_examples_backchannel/fast:
	$(MAKE) -f CMakeFiles/client_examples_backchannel.dir/build.make CMakeFiles/client_examples_backchannel.dir/build
.PHONY : client_examples_backchannel/fast

#=============================================================================
# Target rules for targets named client_examples_ppmtest

# Build rule for target.
client_examples_ppmtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 client_examples_ppmtest
.PHONY : client_examples_ppmtest

# fast build rule for target.
client_examples_ppmtest/fast:
	$(MAKE) -f CMakeFiles/client_examples_ppmtest.dir/build.make CMakeFiles/client_examples_ppmtest.dir/build
.PHONY : client_examples_ppmtest/fast

#=============================================================================
# Target rules for targets named examples_backchannel

# Build rule for target.
examples_backchannel: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 examples_backchannel
.PHONY : examples_backchannel

# fast build rule for target.
examples_backchannel/fast:
	$(MAKE) -f CMakeFiles/examples_backchannel.dir/build.make CMakeFiles/examples_backchannel.dir/build
.PHONY : examples_backchannel/fast

#=============================================================================
# Target rules for targets named examples_blooptest

# Build rule for target.
examples_blooptest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 examples_blooptest
.PHONY : examples_blooptest

# fast build rule for target.
examples_blooptest/fast:
	$(MAKE) -f CMakeFiles/examples_blooptest.dir/build.make CMakeFiles/examples_blooptest.dir/build
.PHONY : examples_blooptest/fast

#=============================================================================
# Target rules for targets named examples_camera

# Build rule for target.
examples_camera: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 examples_camera
.PHONY : examples_camera

# fast build rule for target.
examples_camera/fast:
	$(MAKE) -f CMakeFiles/examples_camera.dir/build.make CMakeFiles/examples_camera.dir/build
.PHONY : examples_camera/fast

#=============================================================================
# Target rules for targets named examples_colourmaptest

# Build rule for target.
examples_colourmaptest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 examples_colourmaptest
.PHONY : examples_colourmaptest

# fast build rule for target.
examples_colourmaptest/fast:
	$(MAKE) -f CMakeFiles/examples_colourmaptest.dir/build.make CMakeFiles/examples_colourmaptest.dir/build
.PHONY : examples_colourmaptest/fast

#=============================================================================
# Target rules for targets named examples_example

# Build rule for target.
examples_example: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 examples_example
.PHONY : examples_example

# fast build rule for target.
examples_example/fast:
	$(MAKE) -f CMakeFiles/examples_example.dir/build.make CMakeFiles/examples_example.dir/build
.PHONY : examples_example/fast

#=============================================================================
# Target rules for targets named examples_filetransfer

# Build rule for target.
examples_filetransfer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 examples_filetransfer
.PHONY : examples_filetransfer

# fast build rule for target.
examples_filetransfer/fast:
	$(MAKE) -f CMakeFiles/examples_filetransfer.dir/build.make CMakeFiles/examples_filetransfer.dir/build
.PHONY : examples_filetransfer/fast

#=============================================================================
# Target rules for targets named examples_fontsel

# Build rule for target.
examples_fontsel: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 examples_fontsel
.PHONY : examples_fontsel

# fast build rule for target.
examples_fontsel/fast:
	$(MAKE) -f CMakeFiles/examples_fontsel.dir/build.make CMakeFiles/examples_fontsel.dir/build
.PHONY : examples_fontsel/fast

#=============================================================================
# Target rules for targets named examples_pnmshow

# Build rule for target.
examples_pnmshow: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 examples_pnmshow
.PHONY : examples_pnmshow

# fast build rule for target.
examples_pnmshow/fast:
	$(MAKE) -f CMakeFiles/examples_pnmshow.dir/build.make CMakeFiles/examples_pnmshow.dir/build
.PHONY : examples_pnmshow/fast

#=============================================================================
# Target rules for targets named examples_pnmshow24

# Build rule for target.
examples_pnmshow24: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 examples_pnmshow24
.PHONY : examples_pnmshow24

# fast build rule for target.
examples_pnmshow24/fast:
	$(MAKE) -f CMakeFiles/examples_pnmshow24.dir/build.make CMakeFiles/examples_pnmshow24.dir/build
.PHONY : examples_pnmshow24/fast

#=============================================================================
# Target rules for targets named examples_regiontest

# Build rule for target.
examples_regiontest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 examples_regiontest
.PHONY : examples_regiontest

# fast build rule for target.
examples_regiontest/fast:
	$(MAKE) -f CMakeFiles/examples_regiontest.dir/build.make CMakeFiles/examples_regiontest.dir/build
.PHONY : examples_regiontest/fast

#=============================================================================
# Target rules for targets named examples_rotate

# Build rule for target.
examples_rotate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 examples_rotate
.PHONY : examples_rotate

# fast build rule for target.
examples_rotate/fast:
	$(MAKE) -f CMakeFiles/examples_rotate.dir/build.make CMakeFiles/examples_rotate.dir/build
.PHONY : examples_rotate/fast

#=============================================================================
# Target rules for targets named examples_simple

# Build rule for target.
examples_simple: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 examples_simple
.PHONY : examples_simple

# fast build rule for target.
examples_simple/fast:
	$(MAKE) -f CMakeFiles/examples_simple.dir/build.make CMakeFiles/examples_simple.dir/build
.PHONY : examples_simple/fast

#=============================================================================
# Target rules for targets named examples_simple15

# Build rule for target.
examples_simple15: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 examples_simple15
.PHONY : examples_simple15

# fast build rule for target.
examples_simple15/fast:
	$(MAKE) -f CMakeFiles/examples_simple15.dir/build.make CMakeFiles/examples_simple15.dir/build
.PHONY : examples_simple15/fast

#=============================================================================
# Target rules for targets named examples_storepasswd

# Build rule for target.
examples_storepasswd: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 examples_storepasswd
.PHONY : examples_storepasswd

# fast build rule for target.
examples_storepasswd/fast:
	$(MAKE) -f CMakeFiles/examples_storepasswd.dir/build.make CMakeFiles/examples_storepasswd.dir/build
.PHONY : examples_storepasswd/fast

#=============================================================================
# Target rules for targets named examples_vncev

# Build rule for target.
examples_vncev: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 examples_vncev
.PHONY : examples_vncev

# fast build rule for target.
examples_vncev/fast:
	$(MAKE) -f CMakeFiles/examples_vncev.dir/build.make CMakeFiles/examples_vncev.dir/build
.PHONY : examples_vncev/fast

#=============================================================================
# Target rules for targets named vncclient

# Build rule for target.
vncclient: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vncclient
.PHONY : vncclient

# fast build rule for target.
vncclient/fast:
	$(MAKE) -f CMakeFiles/vncclient.dir/build.make CMakeFiles/vncclient.dir/build
.PHONY : vncclient/fast

#=============================================================================
# Target rules for targets named vncserver

# Build rule for target.
vncserver: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vncserver
.PHONY : vncserver

# fast build rule for target.
vncserver/fast:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/build
.PHONY : vncserver/fast

client_examples/SDLvncviewer.o: client_examples/SDLvncviewer.c.o
.PHONY : client_examples/SDLvncviewer.o

# target to build an object file
client_examples/SDLvncviewer.c.o:
	$(MAKE) -f CMakeFiles/client_examples_SDLvncviewer.dir/build.make CMakeFiles/client_examples_SDLvncviewer.dir/client_examples/SDLvncviewer.c.o
.PHONY : client_examples/SDLvncviewer.c.o

client_examples/SDLvncviewer.i: client_examples/SDLvncviewer.c.i
.PHONY : client_examples/SDLvncviewer.i

# target to preprocess a source file
client_examples/SDLvncviewer.c.i:
	$(MAKE) -f CMakeFiles/client_examples_SDLvncviewer.dir/build.make CMakeFiles/client_examples_SDLvncviewer.dir/client_examples/SDLvncviewer.c.i
.PHONY : client_examples/SDLvncviewer.c.i

client_examples/SDLvncviewer.s: client_examples/SDLvncviewer.c.s
.PHONY : client_examples/SDLvncviewer.s

# target to generate assembly for a file
client_examples/SDLvncviewer.c.s:
	$(MAKE) -f CMakeFiles/client_examples_SDLvncviewer.dir/build.make CMakeFiles/client_examples_SDLvncviewer.dir/client_examples/SDLvncviewer.c.s
.PHONY : client_examples/SDLvncviewer.c.s

client_examples/backchannel.o: client_examples/backchannel.c.o
.PHONY : client_examples/backchannel.o

# target to build an object file
client_examples/backchannel.c.o:
	$(MAKE) -f CMakeFiles/client_examples_backchannel.dir/build.make CMakeFiles/client_examples_backchannel.dir/client_examples/backchannel.c.o
.PHONY : client_examples/backchannel.c.o

client_examples/backchannel.i: client_examples/backchannel.c.i
.PHONY : client_examples/backchannel.i

# target to preprocess a source file
client_examples/backchannel.c.i:
	$(MAKE) -f CMakeFiles/client_examples_backchannel.dir/build.make CMakeFiles/client_examples_backchannel.dir/client_examples/backchannel.c.i
.PHONY : client_examples/backchannel.c.i

client_examples/backchannel.s: client_examples/backchannel.c.s
.PHONY : client_examples/backchannel.s

# target to generate assembly for a file
client_examples/backchannel.c.s:
	$(MAKE) -f CMakeFiles/client_examples_backchannel.dir/build.make CMakeFiles/client_examples_backchannel.dir/client_examples/backchannel.c.s
.PHONY : client_examples/backchannel.c.s

client_examples/ppmtest.o: client_examples/ppmtest.c.o
.PHONY : client_examples/ppmtest.o

# target to build an object file
client_examples/ppmtest.c.o:
	$(MAKE) -f CMakeFiles/client_examples_ppmtest.dir/build.make CMakeFiles/client_examples_ppmtest.dir/client_examples/ppmtest.c.o
.PHONY : client_examples/ppmtest.c.o

client_examples/ppmtest.i: client_examples/ppmtest.c.i
.PHONY : client_examples/ppmtest.i

# target to preprocess a source file
client_examples/ppmtest.c.i:
	$(MAKE) -f CMakeFiles/client_examples_ppmtest.dir/build.make CMakeFiles/client_examples_ppmtest.dir/client_examples/ppmtest.c.i
.PHONY : client_examples/ppmtest.c.i

client_examples/ppmtest.s: client_examples/ppmtest.c.s
.PHONY : client_examples/ppmtest.s

# target to generate assembly for a file
client_examples/ppmtest.c.s:
	$(MAKE) -f CMakeFiles/client_examples_ppmtest.dir/build.make CMakeFiles/client_examples_ppmtest.dir/client_examples/ppmtest.c.s
.PHONY : client_examples/ppmtest.c.s

client_examples/scrap.o: client_examples/scrap.c.o
.PHONY : client_examples/scrap.o

# target to build an object file
client_examples/scrap.c.o:
	$(MAKE) -f CMakeFiles/client_examples_SDLvncviewer.dir/build.make CMakeFiles/client_examples_SDLvncviewer.dir/client_examples/scrap.c.o
.PHONY : client_examples/scrap.c.o

client_examples/scrap.i: client_examples/scrap.c.i
.PHONY : client_examples/scrap.i

# target to preprocess a source file
client_examples/scrap.c.i:
	$(MAKE) -f CMakeFiles/client_examples_SDLvncviewer.dir/build.make CMakeFiles/client_examples_SDLvncviewer.dir/client_examples/scrap.c.i
.PHONY : client_examples/scrap.c.i

client_examples/scrap.s: client_examples/scrap.c.s
.PHONY : client_examples/scrap.s

# target to generate assembly for a file
client_examples/scrap.c.s:
	$(MAKE) -f CMakeFiles/client_examples_SDLvncviewer.dir/build.make CMakeFiles/client_examples_SDLvncviewer.dir/client_examples/scrap.c.s
.PHONY : client_examples/scrap.c.s

common/d3des.o: common/d3des.c.o
.PHONY : common/d3des.o

# target to build an object file
common/d3des.c.o:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/common/d3des.c.o
.PHONY : common/d3des.c.o

common/d3des.i: common/d3des.c.i
.PHONY : common/d3des.i

# target to preprocess a source file
common/d3des.c.i:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/common/d3des.c.i
.PHONY : common/d3des.c.i

common/d3des.s: common/d3des.c.s
.PHONY : common/d3des.s

# target to generate assembly for a file
common/d3des.c.s:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/common/d3des.c.s
.PHONY : common/d3des.c.s

common/minilzo.o: common/minilzo.c.o
.PHONY : common/minilzo.o

# target to build an object file
common/minilzo.c.o:
	$(MAKE) -f CMakeFiles/vncclient.dir/build.make CMakeFiles/vncclient.dir/common/minilzo.c.o
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/common/minilzo.c.o
.PHONY : common/minilzo.c.o

common/minilzo.i: common/minilzo.c.i
.PHONY : common/minilzo.i

# target to preprocess a source file
common/minilzo.c.i:
	$(MAKE) -f CMakeFiles/vncclient.dir/build.make CMakeFiles/vncclient.dir/common/minilzo.c.i
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/common/minilzo.c.i
.PHONY : common/minilzo.c.i

common/minilzo.s: common/minilzo.c.s
.PHONY : common/minilzo.s

# target to generate assembly for a file
common/minilzo.c.s:
	$(MAKE) -f CMakeFiles/vncclient.dir/build.make CMakeFiles/vncclient.dir/common/minilzo.c.s
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/common/minilzo.c.s
.PHONY : common/minilzo.c.s

common/turbojpeg.o: common/turbojpeg.c.o
.PHONY : common/turbojpeg.o

# target to build an object file
common/turbojpeg.c.o:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/common/turbojpeg.c.o
.PHONY : common/turbojpeg.c.o

common/turbojpeg.i: common/turbojpeg.c.i
.PHONY : common/turbojpeg.i

# target to preprocess a source file
common/turbojpeg.c.i:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/common/turbojpeg.c.i
.PHONY : common/turbojpeg.c.i

common/turbojpeg.s: common/turbojpeg.c.s
.PHONY : common/turbojpeg.s

# target to generate assembly for a file
common/turbojpeg.c.s:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/common/turbojpeg.c.s
.PHONY : common/turbojpeg.c.s

common/vncauth.o: common/vncauth.c.o
.PHONY : common/vncauth.o

# target to build an object file
common/vncauth.c.o:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/common/vncauth.c.o
.PHONY : common/vncauth.c.o

common/vncauth.i: common/vncauth.c.i
.PHONY : common/vncauth.i

# target to preprocess a source file
common/vncauth.c.i:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/common/vncauth.c.i
.PHONY : common/vncauth.c.i

common/vncauth.s: common/vncauth.c.s
.PHONY : common/vncauth.s

# target to generate assembly for a file
common/vncauth.c.s:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/common/vncauth.c.s
.PHONY : common/vncauth.c.s

examples/backchannel.o: examples/backchannel.c.o
.PHONY : examples/backchannel.o

# target to build an object file
examples/backchannel.c.o:
	$(MAKE) -f CMakeFiles/examples_backchannel.dir/build.make CMakeFiles/examples_backchannel.dir/examples/backchannel.c.o
.PHONY : examples/backchannel.c.o

examples/backchannel.i: examples/backchannel.c.i
.PHONY : examples/backchannel.i

# target to preprocess a source file
examples/backchannel.c.i:
	$(MAKE) -f CMakeFiles/examples_backchannel.dir/build.make CMakeFiles/examples_backchannel.dir/examples/backchannel.c.i
.PHONY : examples/backchannel.c.i

examples/backchannel.s: examples/backchannel.c.s
.PHONY : examples/backchannel.s

# target to generate assembly for a file
examples/backchannel.c.s:
	$(MAKE) -f CMakeFiles/examples_backchannel.dir/build.make CMakeFiles/examples_backchannel.dir/examples/backchannel.c.s
.PHONY : examples/backchannel.c.s

examples/blooptest.o: examples/blooptest.c.o
.PHONY : examples/blooptest.o

# target to build an object file
examples/blooptest.c.o:
	$(MAKE) -f CMakeFiles/examples_blooptest.dir/build.make CMakeFiles/examples_blooptest.dir/examples/blooptest.c.o
.PHONY : examples/blooptest.c.o

examples/blooptest.i: examples/blooptest.c.i
.PHONY : examples/blooptest.i

# target to preprocess a source file
examples/blooptest.c.i:
	$(MAKE) -f CMakeFiles/examples_blooptest.dir/build.make CMakeFiles/examples_blooptest.dir/examples/blooptest.c.i
.PHONY : examples/blooptest.c.i

examples/blooptest.s: examples/blooptest.c.s
.PHONY : examples/blooptest.s

# target to generate assembly for a file
examples/blooptest.c.s:
	$(MAKE) -f CMakeFiles/examples_blooptest.dir/build.make CMakeFiles/examples_blooptest.dir/examples/blooptest.c.s
.PHONY : examples/blooptest.c.s

examples/camera.o: examples/camera.c.o
.PHONY : examples/camera.o

# target to build an object file
examples/camera.c.o:
	$(MAKE) -f CMakeFiles/examples_camera.dir/build.make CMakeFiles/examples_camera.dir/examples/camera.c.o
.PHONY : examples/camera.c.o

examples/camera.i: examples/camera.c.i
.PHONY : examples/camera.i

# target to preprocess a source file
examples/camera.c.i:
	$(MAKE) -f CMakeFiles/examples_camera.dir/build.make CMakeFiles/examples_camera.dir/examples/camera.c.i
.PHONY : examples/camera.c.i

examples/camera.s: examples/camera.c.s
.PHONY : examples/camera.s

# target to generate assembly for a file
examples/camera.c.s:
	$(MAKE) -f CMakeFiles/examples_camera.dir/build.make CMakeFiles/examples_camera.dir/examples/camera.c.s
.PHONY : examples/camera.c.s

examples/colourmaptest.o: examples/colourmaptest.c.o
.PHONY : examples/colourmaptest.o

# target to build an object file
examples/colourmaptest.c.o:
	$(MAKE) -f CMakeFiles/examples_colourmaptest.dir/build.make CMakeFiles/examples_colourmaptest.dir/examples/colourmaptest.c.o
.PHONY : examples/colourmaptest.c.o

examples/colourmaptest.i: examples/colourmaptest.c.i
.PHONY : examples/colourmaptest.i

# target to preprocess a source file
examples/colourmaptest.c.i:
	$(MAKE) -f CMakeFiles/examples_colourmaptest.dir/build.make CMakeFiles/examples_colourmaptest.dir/examples/colourmaptest.c.i
.PHONY : examples/colourmaptest.c.i

examples/colourmaptest.s: examples/colourmaptest.c.s
.PHONY : examples/colourmaptest.s

# target to generate assembly for a file
examples/colourmaptest.c.s:
	$(MAKE) -f CMakeFiles/examples_colourmaptest.dir/build.make CMakeFiles/examples_colourmaptest.dir/examples/colourmaptest.c.s
.PHONY : examples/colourmaptest.c.s

examples/example.o: examples/example.c.o
.PHONY : examples/example.o

# target to build an object file
examples/example.c.o:
	$(MAKE) -f CMakeFiles/examples_example.dir/build.make CMakeFiles/examples_example.dir/examples/example.c.o
.PHONY : examples/example.c.o

examples/example.i: examples/example.c.i
.PHONY : examples/example.i

# target to preprocess a source file
examples/example.c.i:
	$(MAKE) -f CMakeFiles/examples_example.dir/build.make CMakeFiles/examples_example.dir/examples/example.c.i
.PHONY : examples/example.c.i

examples/example.s: examples/example.c.s
.PHONY : examples/example.s

# target to generate assembly for a file
examples/example.c.s:
	$(MAKE) -f CMakeFiles/examples_example.dir/build.make CMakeFiles/examples_example.dir/examples/example.c.s
.PHONY : examples/example.c.s

examples/filetransfer.o: examples/filetransfer.c.o
.PHONY : examples/filetransfer.o

# target to build an object file
examples/filetransfer.c.o:
	$(MAKE) -f CMakeFiles/examples_filetransfer.dir/build.make CMakeFiles/examples_filetransfer.dir/examples/filetransfer.c.o
.PHONY : examples/filetransfer.c.o

examples/filetransfer.i: examples/filetransfer.c.i
.PHONY : examples/filetransfer.i

# target to preprocess a source file
examples/filetransfer.c.i:
	$(MAKE) -f CMakeFiles/examples_filetransfer.dir/build.make CMakeFiles/examples_filetransfer.dir/examples/filetransfer.c.i
.PHONY : examples/filetransfer.c.i

examples/filetransfer.s: examples/filetransfer.c.s
.PHONY : examples/filetransfer.s

# target to generate assembly for a file
examples/filetransfer.c.s:
	$(MAKE) -f CMakeFiles/examples_filetransfer.dir/build.make CMakeFiles/examples_filetransfer.dir/examples/filetransfer.c.s
.PHONY : examples/filetransfer.c.s

examples/fontsel.o: examples/fontsel.c.o
.PHONY : examples/fontsel.o

# target to build an object file
examples/fontsel.c.o:
	$(MAKE) -f CMakeFiles/examples_fontsel.dir/build.make CMakeFiles/examples_fontsel.dir/examples/fontsel.c.o
.PHONY : examples/fontsel.c.o

examples/fontsel.i: examples/fontsel.c.i
.PHONY : examples/fontsel.i

# target to preprocess a source file
examples/fontsel.c.i:
	$(MAKE) -f CMakeFiles/examples_fontsel.dir/build.make CMakeFiles/examples_fontsel.dir/examples/fontsel.c.i
.PHONY : examples/fontsel.c.i

examples/fontsel.s: examples/fontsel.c.s
.PHONY : examples/fontsel.s

# target to generate assembly for a file
examples/fontsel.c.s:
	$(MAKE) -f CMakeFiles/examples_fontsel.dir/build.make CMakeFiles/examples_fontsel.dir/examples/fontsel.c.s
.PHONY : examples/fontsel.c.s

examples/pnmshow.o: examples/pnmshow.c.o
.PHONY : examples/pnmshow.o

# target to build an object file
examples/pnmshow.c.o:
	$(MAKE) -f CMakeFiles/examples_pnmshow.dir/build.make CMakeFiles/examples_pnmshow.dir/examples/pnmshow.c.o
.PHONY : examples/pnmshow.c.o

examples/pnmshow.i: examples/pnmshow.c.i
.PHONY : examples/pnmshow.i

# target to preprocess a source file
examples/pnmshow.c.i:
	$(MAKE) -f CMakeFiles/examples_pnmshow.dir/build.make CMakeFiles/examples_pnmshow.dir/examples/pnmshow.c.i
.PHONY : examples/pnmshow.c.i

examples/pnmshow.s: examples/pnmshow.c.s
.PHONY : examples/pnmshow.s

# target to generate assembly for a file
examples/pnmshow.c.s:
	$(MAKE) -f CMakeFiles/examples_pnmshow.dir/build.make CMakeFiles/examples_pnmshow.dir/examples/pnmshow.c.s
.PHONY : examples/pnmshow.c.s

examples/pnmshow24.o: examples/pnmshow24.c.o
.PHONY : examples/pnmshow24.o

# target to build an object file
examples/pnmshow24.c.o:
	$(MAKE) -f CMakeFiles/examples_pnmshow24.dir/build.make CMakeFiles/examples_pnmshow24.dir/examples/pnmshow24.c.o
.PHONY : examples/pnmshow24.c.o

examples/pnmshow24.i: examples/pnmshow24.c.i
.PHONY : examples/pnmshow24.i

# target to preprocess a source file
examples/pnmshow24.c.i:
	$(MAKE) -f CMakeFiles/examples_pnmshow24.dir/build.make CMakeFiles/examples_pnmshow24.dir/examples/pnmshow24.c.i
.PHONY : examples/pnmshow24.c.i

examples/pnmshow24.s: examples/pnmshow24.c.s
.PHONY : examples/pnmshow24.s

# target to generate assembly for a file
examples/pnmshow24.c.s:
	$(MAKE) -f CMakeFiles/examples_pnmshow24.dir/build.make CMakeFiles/examples_pnmshow24.dir/examples/pnmshow24.c.s
.PHONY : examples/pnmshow24.c.s

examples/regiontest.o: examples/regiontest.c.o
.PHONY : examples/regiontest.o

# target to build an object file
examples/regiontest.c.o:
	$(MAKE) -f CMakeFiles/examples_regiontest.dir/build.make CMakeFiles/examples_regiontest.dir/examples/regiontest.c.o
.PHONY : examples/regiontest.c.o

examples/regiontest.i: examples/regiontest.c.i
.PHONY : examples/regiontest.i

# target to preprocess a source file
examples/regiontest.c.i:
	$(MAKE) -f CMakeFiles/examples_regiontest.dir/build.make CMakeFiles/examples_regiontest.dir/examples/regiontest.c.i
.PHONY : examples/regiontest.c.i

examples/regiontest.s: examples/regiontest.c.s
.PHONY : examples/regiontest.s

# target to generate assembly for a file
examples/regiontest.c.s:
	$(MAKE) -f CMakeFiles/examples_regiontest.dir/build.make CMakeFiles/examples_regiontest.dir/examples/regiontest.c.s
.PHONY : examples/regiontest.c.s

examples/rotate.o: examples/rotate.c.o
.PHONY : examples/rotate.o

# target to build an object file
examples/rotate.c.o:
	$(MAKE) -f CMakeFiles/examples_rotate.dir/build.make CMakeFiles/examples_rotate.dir/examples/rotate.c.o
.PHONY : examples/rotate.c.o

examples/rotate.i: examples/rotate.c.i
.PHONY : examples/rotate.i

# target to preprocess a source file
examples/rotate.c.i:
	$(MAKE) -f CMakeFiles/examples_rotate.dir/build.make CMakeFiles/examples_rotate.dir/examples/rotate.c.i
.PHONY : examples/rotate.c.i

examples/rotate.s: examples/rotate.c.s
.PHONY : examples/rotate.s

# target to generate assembly for a file
examples/rotate.c.s:
	$(MAKE) -f CMakeFiles/examples_rotate.dir/build.make CMakeFiles/examples_rotate.dir/examples/rotate.c.s
.PHONY : examples/rotate.c.s

examples/simple.o: examples/simple.c.o
.PHONY : examples/simple.o

# target to build an object file
examples/simple.c.o:
	$(MAKE) -f CMakeFiles/examples_simple.dir/build.make CMakeFiles/examples_simple.dir/examples/simple.c.o
.PHONY : examples/simple.c.o

examples/simple.i: examples/simple.c.i
.PHONY : examples/simple.i

# target to preprocess a source file
examples/simple.c.i:
	$(MAKE) -f CMakeFiles/examples_simple.dir/build.make CMakeFiles/examples_simple.dir/examples/simple.c.i
.PHONY : examples/simple.c.i

examples/simple.s: examples/simple.c.s
.PHONY : examples/simple.s

# target to generate assembly for a file
examples/simple.c.s:
	$(MAKE) -f CMakeFiles/examples_simple.dir/build.make CMakeFiles/examples_simple.dir/examples/simple.c.s
.PHONY : examples/simple.c.s

examples/simple15.o: examples/simple15.c.o
.PHONY : examples/simple15.o

# target to build an object file
examples/simple15.c.o:
	$(MAKE) -f CMakeFiles/examples_simple15.dir/build.make CMakeFiles/examples_simple15.dir/examples/simple15.c.o
.PHONY : examples/simple15.c.o

examples/simple15.i: examples/simple15.c.i
.PHONY : examples/simple15.i

# target to preprocess a source file
examples/simple15.c.i:
	$(MAKE) -f CMakeFiles/examples_simple15.dir/build.make CMakeFiles/examples_simple15.dir/examples/simple15.c.i
.PHONY : examples/simple15.c.i

examples/simple15.s: examples/simple15.c.s
.PHONY : examples/simple15.s

# target to generate assembly for a file
examples/simple15.c.s:
	$(MAKE) -f CMakeFiles/examples_simple15.dir/build.make CMakeFiles/examples_simple15.dir/examples/simple15.c.s
.PHONY : examples/simple15.c.s

examples/storepasswd.o: examples/storepasswd.c.o
.PHONY : examples/storepasswd.o

# target to build an object file
examples/storepasswd.c.o:
	$(MAKE) -f CMakeFiles/examples_storepasswd.dir/build.make CMakeFiles/examples_storepasswd.dir/examples/storepasswd.c.o
.PHONY : examples/storepasswd.c.o

examples/storepasswd.i: examples/storepasswd.c.i
.PHONY : examples/storepasswd.i

# target to preprocess a source file
examples/storepasswd.c.i:
	$(MAKE) -f CMakeFiles/examples_storepasswd.dir/build.make CMakeFiles/examples_storepasswd.dir/examples/storepasswd.c.i
.PHONY : examples/storepasswd.c.i

examples/storepasswd.s: examples/storepasswd.c.s
.PHONY : examples/storepasswd.s

# target to generate assembly for a file
examples/storepasswd.c.s:
	$(MAKE) -f CMakeFiles/examples_storepasswd.dir/build.make CMakeFiles/examples_storepasswd.dir/examples/storepasswd.c.s
.PHONY : examples/storepasswd.c.s

examples/vncev.o: examples/vncev.c.o
.PHONY : examples/vncev.o

# target to build an object file
examples/vncev.c.o:
	$(MAKE) -f CMakeFiles/examples_vncev.dir/build.make CMakeFiles/examples_vncev.dir/examples/vncev.c.o
.PHONY : examples/vncev.c.o

examples/vncev.i: examples/vncev.c.i
.PHONY : examples/vncev.i

# target to preprocess a source file
examples/vncev.c.i:
	$(MAKE) -f CMakeFiles/examples_vncev.dir/build.make CMakeFiles/examples_vncev.dir/examples/vncev.c.i
.PHONY : examples/vncev.c.i

examples/vncev.s: examples/vncev.c.s
.PHONY : examples/vncev.s

# target to generate assembly for a file
examples/vncev.c.s:
	$(MAKE) -f CMakeFiles/examples_vncev.dir/build.make CMakeFiles/examples_vncev.dir/examples/vncev.c.s
.PHONY : examples/vncev.c.s

libvncclient/cursor.o: libvncclient/cursor.c.o
.PHONY : libvncclient/cursor.o

# target to build an object file
libvncclient/cursor.c.o:
	$(MAKE) -f CMakeFiles/vncclient.dir/build.make CMakeFiles/vncclient.dir/libvncclient/cursor.c.o
.PHONY : libvncclient/cursor.c.o

libvncclient/cursor.i: libvncclient/cursor.c.i
.PHONY : libvncclient/cursor.i

# target to preprocess a source file
libvncclient/cursor.c.i:
	$(MAKE) -f CMakeFiles/vncclient.dir/build.make CMakeFiles/vncclient.dir/libvncclient/cursor.c.i
.PHONY : libvncclient/cursor.c.i

libvncclient/cursor.s: libvncclient/cursor.c.s
.PHONY : libvncclient/cursor.s

# target to generate assembly for a file
libvncclient/cursor.c.s:
	$(MAKE) -f CMakeFiles/vncclient.dir/build.make CMakeFiles/vncclient.dir/libvncclient/cursor.c.s
.PHONY : libvncclient/cursor.c.s

libvncclient/listen.o: libvncclient/listen.c.o
.PHONY : libvncclient/listen.o

# target to build an object file
libvncclient/listen.c.o:
	$(MAKE) -f CMakeFiles/vncclient.dir/build.make CMakeFiles/vncclient.dir/libvncclient/listen.c.o
.PHONY : libvncclient/listen.c.o

libvncclient/listen.i: libvncclient/listen.c.i
.PHONY : libvncclient/listen.i

# target to preprocess a source file
libvncclient/listen.c.i:
	$(MAKE) -f CMakeFiles/vncclient.dir/build.make CMakeFiles/vncclient.dir/libvncclient/listen.c.i
.PHONY : libvncclient/listen.c.i

libvncclient/listen.s: libvncclient/listen.c.s
.PHONY : libvncclient/listen.s

# target to generate assembly for a file
libvncclient/listen.c.s:
	$(MAKE) -f CMakeFiles/vncclient.dir/build.make CMakeFiles/vncclient.dir/libvncclient/listen.c.s
.PHONY : libvncclient/listen.c.s

libvncclient/rfbproto.o: libvncclient/rfbproto.c.o
.PHONY : libvncclient/rfbproto.o

# target to build an object file
libvncclient/rfbproto.c.o:
	$(MAKE) -f CMakeFiles/vncclient.dir/build.make CMakeFiles/vncclient.dir/libvncclient/rfbproto.c.o
.PHONY : libvncclient/rfbproto.c.o

libvncclient/rfbproto.i: libvncclient/rfbproto.c.i
.PHONY : libvncclient/rfbproto.i

# target to preprocess a source file
libvncclient/rfbproto.c.i:
	$(MAKE) -f CMakeFiles/vncclient.dir/build.make CMakeFiles/vncclient.dir/libvncclient/rfbproto.c.i
.PHONY : libvncclient/rfbproto.c.i

libvncclient/rfbproto.s: libvncclient/rfbproto.c.s
.PHONY : libvncclient/rfbproto.s

# target to generate assembly for a file
libvncclient/rfbproto.c.s:
	$(MAKE) -f CMakeFiles/vncclient.dir/build.make CMakeFiles/vncclient.dir/libvncclient/rfbproto.c.s
.PHONY : libvncclient/rfbproto.c.s

libvncclient/sockets.o: libvncclient/sockets.c.o
.PHONY : libvncclient/sockets.o

# target to build an object file
libvncclient/sockets.c.o:
	$(MAKE) -f CMakeFiles/vncclient.dir/build.make CMakeFiles/vncclient.dir/libvncclient/sockets.c.o
.PHONY : libvncclient/sockets.c.o

libvncclient/sockets.i: libvncclient/sockets.c.i
.PHONY : libvncclient/sockets.i

# target to preprocess a source file
libvncclient/sockets.c.i:
	$(MAKE) -f CMakeFiles/vncclient.dir/build.make CMakeFiles/vncclient.dir/libvncclient/sockets.c.i
.PHONY : libvncclient/sockets.c.i

libvncclient/sockets.s: libvncclient/sockets.c.s
.PHONY : libvncclient/sockets.s

# target to generate assembly for a file
libvncclient/sockets.c.s:
	$(MAKE) -f CMakeFiles/vncclient.dir/build.make CMakeFiles/vncclient.dir/libvncclient/sockets.c.s
.PHONY : libvncclient/sockets.c.s

libvncclient/tls_openssl.o: libvncclient/tls_openssl.c.o
.PHONY : libvncclient/tls_openssl.o

# target to build an object file
libvncclient/tls_openssl.c.o:
	$(MAKE) -f CMakeFiles/vncclient.dir/build.make CMakeFiles/vncclient.dir/libvncclient/tls_openssl.c.o
.PHONY : libvncclient/tls_openssl.c.o

libvncclient/tls_openssl.i: libvncclient/tls_openssl.c.i
.PHONY : libvncclient/tls_openssl.i

# target to preprocess a source file
libvncclient/tls_openssl.c.i:
	$(MAKE) -f CMakeFiles/vncclient.dir/build.make CMakeFiles/vncclient.dir/libvncclient/tls_openssl.c.i
.PHONY : libvncclient/tls_openssl.c.i

libvncclient/tls_openssl.s: libvncclient/tls_openssl.c.s
.PHONY : libvncclient/tls_openssl.s

# target to generate assembly for a file
libvncclient/tls_openssl.c.s:
	$(MAKE) -f CMakeFiles/vncclient.dir/build.make CMakeFiles/vncclient.dir/libvncclient/tls_openssl.c.s
.PHONY : libvncclient/tls_openssl.c.s

libvncclient/vncviewer.o: libvncclient/vncviewer.c.o
.PHONY : libvncclient/vncviewer.o

# target to build an object file
libvncclient/vncviewer.c.o:
	$(MAKE) -f CMakeFiles/vncclient.dir/build.make CMakeFiles/vncclient.dir/libvncclient/vncviewer.c.o
.PHONY : libvncclient/vncviewer.c.o

libvncclient/vncviewer.i: libvncclient/vncviewer.c.i
.PHONY : libvncclient/vncviewer.i

# target to preprocess a source file
libvncclient/vncviewer.c.i:
	$(MAKE) -f CMakeFiles/vncclient.dir/build.make CMakeFiles/vncclient.dir/libvncclient/vncviewer.c.i
.PHONY : libvncclient/vncviewer.c.i

libvncclient/vncviewer.s: libvncclient/vncviewer.c.s
.PHONY : libvncclient/vncviewer.s

# target to generate assembly for a file
libvncclient/vncviewer.c.s:
	$(MAKE) -f CMakeFiles/vncclient.dir/build.make CMakeFiles/vncclient.dir/libvncclient/vncviewer.c.s
.PHONY : libvncclient/vncviewer.c.s

libvncserver/auth.o: libvncserver/auth.c.o
.PHONY : libvncserver/auth.o

# target to build an object file
libvncserver/auth.c.o:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/auth.c.o
.PHONY : libvncserver/auth.c.o

libvncserver/auth.i: libvncserver/auth.c.i
.PHONY : libvncserver/auth.i

# target to preprocess a source file
libvncserver/auth.c.i:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/auth.c.i
.PHONY : libvncserver/auth.c.i

libvncserver/auth.s: libvncserver/auth.c.s
.PHONY : libvncserver/auth.s

# target to generate assembly for a file
libvncserver/auth.c.s:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/auth.c.s
.PHONY : libvncserver/auth.c.s

libvncserver/cargs.o: libvncserver/cargs.c.o
.PHONY : libvncserver/cargs.o

# target to build an object file
libvncserver/cargs.c.o:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/cargs.c.o
.PHONY : libvncserver/cargs.c.o

libvncserver/cargs.i: libvncserver/cargs.c.i
.PHONY : libvncserver/cargs.i

# target to preprocess a source file
libvncserver/cargs.c.i:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/cargs.c.i
.PHONY : libvncserver/cargs.c.i

libvncserver/cargs.s: libvncserver/cargs.c.s
.PHONY : libvncserver/cargs.s

# target to generate assembly for a file
libvncserver/cargs.c.s:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/cargs.c.s
.PHONY : libvncserver/cargs.c.s

libvncserver/corre.o: libvncserver/corre.c.o
.PHONY : libvncserver/corre.o

# target to build an object file
libvncserver/corre.c.o:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/corre.c.o
.PHONY : libvncserver/corre.c.o

libvncserver/corre.i: libvncserver/corre.c.i
.PHONY : libvncserver/corre.i

# target to preprocess a source file
libvncserver/corre.c.i:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/corre.c.i
.PHONY : libvncserver/corre.c.i

libvncserver/corre.s: libvncserver/corre.c.s
.PHONY : libvncserver/corre.s

# target to generate assembly for a file
libvncserver/corre.c.s:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/corre.c.s
.PHONY : libvncserver/corre.c.s

libvncserver/cursor.o: libvncserver/cursor.c.o
.PHONY : libvncserver/cursor.o

# target to build an object file
libvncserver/cursor.c.o:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/cursor.c.o
.PHONY : libvncserver/cursor.c.o

libvncserver/cursor.i: libvncserver/cursor.c.i
.PHONY : libvncserver/cursor.i

# target to preprocess a source file
libvncserver/cursor.c.i:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/cursor.c.i
.PHONY : libvncserver/cursor.c.i

libvncserver/cursor.s: libvncserver/cursor.c.s
.PHONY : libvncserver/cursor.s

# target to generate assembly for a file
libvncserver/cursor.c.s:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/cursor.c.s
.PHONY : libvncserver/cursor.c.s

libvncserver/cutpaste.o: libvncserver/cutpaste.c.o
.PHONY : libvncserver/cutpaste.o

# target to build an object file
libvncserver/cutpaste.c.o:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/cutpaste.c.o
.PHONY : libvncserver/cutpaste.c.o

libvncserver/cutpaste.i: libvncserver/cutpaste.c.i
.PHONY : libvncserver/cutpaste.i

# target to preprocess a source file
libvncserver/cutpaste.c.i:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/cutpaste.c.i
.PHONY : libvncserver/cutpaste.c.i

libvncserver/cutpaste.s: libvncserver/cutpaste.c.s
.PHONY : libvncserver/cutpaste.s

# target to generate assembly for a file
libvncserver/cutpaste.c.s:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/cutpaste.c.s
.PHONY : libvncserver/cutpaste.c.s

libvncserver/draw.o: libvncserver/draw.c.o
.PHONY : libvncserver/draw.o

# target to build an object file
libvncserver/draw.c.o:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/draw.c.o
.PHONY : libvncserver/draw.c.o

libvncserver/draw.i: libvncserver/draw.c.i
.PHONY : libvncserver/draw.i

# target to preprocess a source file
libvncserver/draw.c.i:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/draw.c.i
.PHONY : libvncserver/draw.c.i

libvncserver/draw.s: libvncserver/draw.c.s
.PHONY : libvncserver/draw.s

# target to generate assembly for a file
libvncserver/draw.c.s:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/draw.c.s
.PHONY : libvncserver/draw.c.s

libvncserver/font.o: libvncserver/font.c.o
.PHONY : libvncserver/font.o

# target to build an object file
libvncserver/font.c.o:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/font.c.o
.PHONY : libvncserver/font.c.o

libvncserver/font.i: libvncserver/font.c.i
.PHONY : libvncserver/font.i

# target to preprocess a source file
libvncserver/font.c.i:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/font.c.i
.PHONY : libvncserver/font.c.i

libvncserver/font.s: libvncserver/font.c.s
.PHONY : libvncserver/font.s

# target to generate assembly for a file
libvncserver/font.c.s:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/font.c.s
.PHONY : libvncserver/font.c.s

libvncserver/hextile.o: libvncserver/hextile.c.o
.PHONY : libvncserver/hextile.o

# target to build an object file
libvncserver/hextile.c.o:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/hextile.c.o
.PHONY : libvncserver/hextile.c.o

libvncserver/hextile.i: libvncserver/hextile.c.i
.PHONY : libvncserver/hextile.i

# target to preprocess a source file
libvncserver/hextile.c.i:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/hextile.c.i
.PHONY : libvncserver/hextile.c.i

libvncserver/hextile.s: libvncserver/hextile.c.s
.PHONY : libvncserver/hextile.s

# target to generate assembly for a file
libvncserver/hextile.c.s:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/hextile.c.s
.PHONY : libvncserver/hextile.c.s

libvncserver/httpd.o: libvncserver/httpd.c.o
.PHONY : libvncserver/httpd.o

# target to build an object file
libvncserver/httpd.c.o:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/httpd.c.o
.PHONY : libvncserver/httpd.c.o

libvncserver/httpd.i: libvncserver/httpd.c.i
.PHONY : libvncserver/httpd.i

# target to preprocess a source file
libvncserver/httpd.c.i:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/httpd.c.i
.PHONY : libvncserver/httpd.c.i

libvncserver/httpd.s: libvncserver/httpd.c.s
.PHONY : libvncserver/httpd.s

# target to generate assembly for a file
libvncserver/httpd.c.s:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/httpd.c.s
.PHONY : libvncserver/httpd.c.s

libvncserver/main.o: libvncserver/main.c.o
.PHONY : libvncserver/main.o

# target to build an object file
libvncserver/main.c.o:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/main.c.o
.PHONY : libvncserver/main.c.o

libvncserver/main.i: libvncserver/main.c.i
.PHONY : libvncserver/main.i

# target to preprocess a source file
libvncserver/main.c.i:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/main.c.i
.PHONY : libvncserver/main.c.i

libvncserver/main.s: libvncserver/main.c.s
.PHONY : libvncserver/main.s

# target to generate assembly for a file
libvncserver/main.c.s:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/main.c.s
.PHONY : libvncserver/main.c.s

libvncserver/rfbcrypto_openssl.o: libvncserver/rfbcrypto_openssl.c.o
.PHONY : libvncserver/rfbcrypto_openssl.o

# target to build an object file
libvncserver/rfbcrypto_openssl.c.o:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/rfbcrypto_openssl.c.o
.PHONY : libvncserver/rfbcrypto_openssl.c.o

libvncserver/rfbcrypto_openssl.i: libvncserver/rfbcrypto_openssl.c.i
.PHONY : libvncserver/rfbcrypto_openssl.i

# target to preprocess a source file
libvncserver/rfbcrypto_openssl.c.i:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/rfbcrypto_openssl.c.i
.PHONY : libvncserver/rfbcrypto_openssl.c.i

libvncserver/rfbcrypto_openssl.s: libvncserver/rfbcrypto_openssl.c.s
.PHONY : libvncserver/rfbcrypto_openssl.s

# target to generate assembly for a file
libvncserver/rfbcrypto_openssl.c.s:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/rfbcrypto_openssl.c.s
.PHONY : libvncserver/rfbcrypto_openssl.c.s

libvncserver/rfbregion.o: libvncserver/rfbregion.c.o
.PHONY : libvncserver/rfbregion.o

# target to build an object file
libvncserver/rfbregion.c.o:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/rfbregion.c.o
.PHONY : libvncserver/rfbregion.c.o

libvncserver/rfbregion.i: libvncserver/rfbregion.c.i
.PHONY : libvncserver/rfbregion.i

# target to preprocess a source file
libvncserver/rfbregion.c.i:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/rfbregion.c.i
.PHONY : libvncserver/rfbregion.c.i

libvncserver/rfbregion.s: libvncserver/rfbregion.c.s
.PHONY : libvncserver/rfbregion.s

# target to generate assembly for a file
libvncserver/rfbregion.c.s:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/rfbregion.c.s
.PHONY : libvncserver/rfbregion.c.s

libvncserver/rfbserver.o: libvncserver/rfbserver.c.o
.PHONY : libvncserver/rfbserver.o

# target to build an object file
libvncserver/rfbserver.c.o:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/rfbserver.c.o
.PHONY : libvncserver/rfbserver.c.o

libvncserver/rfbserver.i: libvncserver/rfbserver.c.i
.PHONY : libvncserver/rfbserver.i

# target to preprocess a source file
libvncserver/rfbserver.c.i:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/rfbserver.c.i
.PHONY : libvncserver/rfbserver.c.i

libvncserver/rfbserver.s: libvncserver/rfbserver.c.s
.PHONY : libvncserver/rfbserver.s

# target to generate assembly for a file
libvncserver/rfbserver.c.s:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/rfbserver.c.s
.PHONY : libvncserver/rfbserver.c.s

libvncserver/rfbssl_openssl.o: libvncserver/rfbssl_openssl.c.o
.PHONY : libvncserver/rfbssl_openssl.o

# target to build an object file
libvncserver/rfbssl_openssl.c.o:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/rfbssl_openssl.c.o
.PHONY : libvncserver/rfbssl_openssl.c.o

libvncserver/rfbssl_openssl.i: libvncserver/rfbssl_openssl.c.i
.PHONY : libvncserver/rfbssl_openssl.i

# target to preprocess a source file
libvncserver/rfbssl_openssl.c.i:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/rfbssl_openssl.c.i
.PHONY : libvncserver/rfbssl_openssl.c.i

libvncserver/rfbssl_openssl.s: libvncserver/rfbssl_openssl.c.s
.PHONY : libvncserver/rfbssl_openssl.s

# target to generate assembly for a file
libvncserver/rfbssl_openssl.c.s:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/rfbssl_openssl.c.s
.PHONY : libvncserver/rfbssl_openssl.c.s

libvncserver/rre.o: libvncserver/rre.c.o
.PHONY : libvncserver/rre.o

# target to build an object file
libvncserver/rre.c.o:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/rre.c.o
.PHONY : libvncserver/rre.c.o

libvncserver/rre.i: libvncserver/rre.c.i
.PHONY : libvncserver/rre.i

# target to preprocess a source file
libvncserver/rre.c.i:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/rre.c.i
.PHONY : libvncserver/rre.c.i

libvncserver/rre.s: libvncserver/rre.c.s
.PHONY : libvncserver/rre.s

# target to generate assembly for a file
libvncserver/rre.c.s:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/rre.c.s
.PHONY : libvncserver/rre.c.s

libvncserver/scale.o: libvncserver/scale.c.o
.PHONY : libvncserver/scale.o

# target to build an object file
libvncserver/scale.c.o:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/scale.c.o
.PHONY : libvncserver/scale.c.o

libvncserver/scale.i: libvncserver/scale.c.i
.PHONY : libvncserver/scale.i

# target to preprocess a source file
libvncserver/scale.c.i:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/scale.c.i
.PHONY : libvncserver/scale.c.i

libvncserver/scale.s: libvncserver/scale.c.s
.PHONY : libvncserver/scale.s

# target to generate assembly for a file
libvncserver/scale.c.s:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/scale.c.s
.PHONY : libvncserver/scale.c.s

libvncserver/selbox.o: libvncserver/selbox.c.o
.PHONY : libvncserver/selbox.o

# target to build an object file
libvncserver/selbox.c.o:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/selbox.c.o
.PHONY : libvncserver/selbox.c.o

libvncserver/selbox.i: libvncserver/selbox.c.i
.PHONY : libvncserver/selbox.i

# target to preprocess a source file
libvncserver/selbox.c.i:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/selbox.c.i
.PHONY : libvncserver/selbox.c.i

libvncserver/selbox.s: libvncserver/selbox.c.s
.PHONY : libvncserver/selbox.s

# target to generate assembly for a file
libvncserver/selbox.c.s:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/selbox.c.s
.PHONY : libvncserver/selbox.c.s

libvncserver/sockets.o: libvncserver/sockets.c.o
.PHONY : libvncserver/sockets.o

# target to build an object file
libvncserver/sockets.c.o:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/sockets.c.o
.PHONY : libvncserver/sockets.c.o

libvncserver/sockets.i: libvncserver/sockets.c.i
.PHONY : libvncserver/sockets.i

# target to preprocess a source file
libvncserver/sockets.c.i:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/sockets.c.i
.PHONY : libvncserver/sockets.c.i

libvncserver/sockets.s: libvncserver/sockets.c.s
.PHONY : libvncserver/sockets.s

# target to generate assembly for a file
libvncserver/sockets.c.s:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/sockets.c.s
.PHONY : libvncserver/sockets.c.s

libvncserver/stats.o: libvncserver/stats.c.o
.PHONY : libvncserver/stats.o

# target to build an object file
libvncserver/stats.c.o:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/stats.c.o
.PHONY : libvncserver/stats.c.o

libvncserver/stats.i: libvncserver/stats.c.i
.PHONY : libvncserver/stats.i

# target to preprocess a source file
libvncserver/stats.c.i:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/stats.c.i
.PHONY : libvncserver/stats.c.i

libvncserver/stats.s: libvncserver/stats.c.s
.PHONY : libvncserver/stats.s

# target to generate assembly for a file
libvncserver/stats.c.s:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/stats.c.s
.PHONY : libvncserver/stats.c.s

libvncserver/tight.o: libvncserver/tight.c.o
.PHONY : libvncserver/tight.o

# target to build an object file
libvncserver/tight.c.o:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/tight.c.o
.PHONY : libvncserver/tight.c.o

libvncserver/tight.i: libvncserver/tight.c.i
.PHONY : libvncserver/tight.i

# target to preprocess a source file
libvncserver/tight.c.i:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/tight.c.i
.PHONY : libvncserver/tight.c.i

libvncserver/tight.s: libvncserver/tight.c.s
.PHONY : libvncserver/tight.s

# target to generate assembly for a file
libvncserver/tight.c.s:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/tight.c.s
.PHONY : libvncserver/tight.c.s

libvncserver/tightvnc-filetransfer/filelistinfo.o: libvncserver/tightvnc-filetransfer/filelistinfo.c.o
.PHONY : libvncserver/tightvnc-filetransfer/filelistinfo.o

# target to build an object file
libvncserver/tightvnc-filetransfer/filelistinfo.c.o:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/tightvnc-filetransfer/filelistinfo.c.o
.PHONY : libvncserver/tightvnc-filetransfer/filelistinfo.c.o

libvncserver/tightvnc-filetransfer/filelistinfo.i: libvncserver/tightvnc-filetransfer/filelistinfo.c.i
.PHONY : libvncserver/tightvnc-filetransfer/filelistinfo.i

# target to preprocess a source file
libvncserver/tightvnc-filetransfer/filelistinfo.c.i:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/tightvnc-filetransfer/filelistinfo.c.i
.PHONY : libvncserver/tightvnc-filetransfer/filelistinfo.c.i

libvncserver/tightvnc-filetransfer/filelistinfo.s: libvncserver/tightvnc-filetransfer/filelistinfo.c.s
.PHONY : libvncserver/tightvnc-filetransfer/filelistinfo.s

# target to generate assembly for a file
libvncserver/tightvnc-filetransfer/filelistinfo.c.s:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/tightvnc-filetransfer/filelistinfo.c.s
.PHONY : libvncserver/tightvnc-filetransfer/filelistinfo.c.s

libvncserver/tightvnc-filetransfer/filetransfermsg.o: libvncserver/tightvnc-filetransfer/filetransfermsg.c.o
.PHONY : libvncserver/tightvnc-filetransfer/filetransfermsg.o

# target to build an object file
libvncserver/tightvnc-filetransfer/filetransfermsg.c.o:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/tightvnc-filetransfer/filetransfermsg.c.o
.PHONY : libvncserver/tightvnc-filetransfer/filetransfermsg.c.o

libvncserver/tightvnc-filetransfer/filetransfermsg.i: libvncserver/tightvnc-filetransfer/filetransfermsg.c.i
.PHONY : libvncserver/tightvnc-filetransfer/filetransfermsg.i

# target to preprocess a source file
libvncserver/tightvnc-filetransfer/filetransfermsg.c.i:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/tightvnc-filetransfer/filetransfermsg.c.i
.PHONY : libvncserver/tightvnc-filetransfer/filetransfermsg.c.i

libvncserver/tightvnc-filetransfer/filetransfermsg.s: libvncserver/tightvnc-filetransfer/filetransfermsg.c.s
.PHONY : libvncserver/tightvnc-filetransfer/filetransfermsg.s

# target to generate assembly for a file
libvncserver/tightvnc-filetransfer/filetransfermsg.c.s:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/tightvnc-filetransfer/filetransfermsg.c.s
.PHONY : libvncserver/tightvnc-filetransfer/filetransfermsg.c.s

libvncserver/tightvnc-filetransfer/handlefiletransferrequest.o: libvncserver/tightvnc-filetransfer/handlefiletransferrequest.c.o
.PHONY : libvncserver/tightvnc-filetransfer/handlefiletransferrequest.o

# target to build an object file
libvncserver/tightvnc-filetransfer/handlefiletransferrequest.c.o:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/tightvnc-filetransfer/handlefiletransferrequest.c.o
.PHONY : libvncserver/tightvnc-filetransfer/handlefiletransferrequest.c.o

libvncserver/tightvnc-filetransfer/handlefiletransferrequest.i: libvncserver/tightvnc-filetransfer/handlefiletransferrequest.c.i
.PHONY : libvncserver/tightvnc-filetransfer/handlefiletransferrequest.i

# target to preprocess a source file
libvncserver/tightvnc-filetransfer/handlefiletransferrequest.c.i:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/tightvnc-filetransfer/handlefiletransferrequest.c.i
.PHONY : libvncserver/tightvnc-filetransfer/handlefiletransferrequest.c.i

libvncserver/tightvnc-filetransfer/handlefiletransferrequest.s: libvncserver/tightvnc-filetransfer/handlefiletransferrequest.c.s
.PHONY : libvncserver/tightvnc-filetransfer/handlefiletransferrequest.s

# target to generate assembly for a file
libvncserver/tightvnc-filetransfer/handlefiletransferrequest.c.s:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/tightvnc-filetransfer/handlefiletransferrequest.c.s
.PHONY : libvncserver/tightvnc-filetransfer/handlefiletransferrequest.c.s

libvncserver/tightvnc-filetransfer/rfbtightserver.o: libvncserver/tightvnc-filetransfer/rfbtightserver.c.o
.PHONY : libvncserver/tightvnc-filetransfer/rfbtightserver.o

# target to build an object file
libvncserver/tightvnc-filetransfer/rfbtightserver.c.o:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/tightvnc-filetransfer/rfbtightserver.c.o
.PHONY : libvncserver/tightvnc-filetransfer/rfbtightserver.c.o

libvncserver/tightvnc-filetransfer/rfbtightserver.i: libvncserver/tightvnc-filetransfer/rfbtightserver.c.i
.PHONY : libvncserver/tightvnc-filetransfer/rfbtightserver.i

# target to preprocess a source file
libvncserver/tightvnc-filetransfer/rfbtightserver.c.i:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/tightvnc-filetransfer/rfbtightserver.c.i
.PHONY : libvncserver/tightvnc-filetransfer/rfbtightserver.c.i

libvncserver/tightvnc-filetransfer/rfbtightserver.s: libvncserver/tightvnc-filetransfer/rfbtightserver.c.s
.PHONY : libvncserver/tightvnc-filetransfer/rfbtightserver.s

# target to generate assembly for a file
libvncserver/tightvnc-filetransfer/rfbtightserver.c.s:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/tightvnc-filetransfer/rfbtightserver.c.s
.PHONY : libvncserver/tightvnc-filetransfer/rfbtightserver.c.s

libvncserver/translate.o: libvncserver/translate.c.o
.PHONY : libvncserver/translate.o

# target to build an object file
libvncserver/translate.c.o:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/translate.c.o
.PHONY : libvncserver/translate.c.o

libvncserver/translate.i: libvncserver/translate.c.i
.PHONY : libvncserver/translate.i

# target to preprocess a source file
libvncserver/translate.c.i:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/translate.c.i
.PHONY : libvncserver/translate.c.i

libvncserver/translate.s: libvncserver/translate.c.s
.PHONY : libvncserver/translate.s

# target to generate assembly for a file
libvncserver/translate.c.s:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/translate.c.s
.PHONY : libvncserver/translate.c.s

libvncserver/ultra.o: libvncserver/ultra.c.o
.PHONY : libvncserver/ultra.o

# target to build an object file
libvncserver/ultra.c.o:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/ultra.c.o
.PHONY : libvncserver/ultra.c.o

libvncserver/ultra.i: libvncserver/ultra.c.i
.PHONY : libvncserver/ultra.i

# target to preprocess a source file
libvncserver/ultra.c.i:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/ultra.c.i
.PHONY : libvncserver/ultra.c.i

libvncserver/ultra.s: libvncserver/ultra.c.s
.PHONY : libvncserver/ultra.s

# target to generate assembly for a file
libvncserver/ultra.c.s:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/ultra.c.s
.PHONY : libvncserver/ultra.c.s

libvncserver/websockets.o: libvncserver/websockets.c.o
.PHONY : libvncserver/websockets.o

# target to build an object file
libvncserver/websockets.c.o:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/websockets.c.o
.PHONY : libvncserver/websockets.c.o

libvncserver/websockets.i: libvncserver/websockets.c.i
.PHONY : libvncserver/websockets.i

# target to preprocess a source file
libvncserver/websockets.c.i:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/websockets.c.i
.PHONY : libvncserver/websockets.c.i

libvncserver/websockets.s: libvncserver/websockets.c.s
.PHONY : libvncserver/websockets.s

# target to generate assembly for a file
libvncserver/websockets.c.s:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/websockets.c.s
.PHONY : libvncserver/websockets.c.s

libvncserver/zlib.o: libvncserver/zlib.c.o
.PHONY : libvncserver/zlib.o

# target to build an object file
libvncserver/zlib.c.o:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/zlib.c.o
.PHONY : libvncserver/zlib.c.o

libvncserver/zlib.i: libvncserver/zlib.c.i
.PHONY : libvncserver/zlib.i

# target to preprocess a source file
libvncserver/zlib.c.i:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/zlib.c.i
.PHONY : libvncserver/zlib.c.i

libvncserver/zlib.s: libvncserver/zlib.c.s
.PHONY : libvncserver/zlib.s

# target to generate assembly for a file
libvncserver/zlib.c.s:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/zlib.c.s
.PHONY : libvncserver/zlib.c.s

libvncserver/zrle.o: libvncserver/zrle.c.o
.PHONY : libvncserver/zrle.o

# target to build an object file
libvncserver/zrle.c.o:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/zrle.c.o
.PHONY : libvncserver/zrle.c.o

libvncserver/zrle.i: libvncserver/zrle.c.i
.PHONY : libvncserver/zrle.i

# target to preprocess a source file
libvncserver/zrle.c.i:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/zrle.c.i
.PHONY : libvncserver/zrle.c.i

libvncserver/zrle.s: libvncserver/zrle.c.s
.PHONY : libvncserver/zrle.s

# target to generate assembly for a file
libvncserver/zrle.c.s:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/zrle.c.s
.PHONY : libvncserver/zrle.c.s

libvncserver/zrleoutstream.o: libvncserver/zrleoutstream.c.o
.PHONY : libvncserver/zrleoutstream.o

# target to build an object file
libvncserver/zrleoutstream.c.o:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/zrleoutstream.c.o
.PHONY : libvncserver/zrleoutstream.c.o

libvncserver/zrleoutstream.i: libvncserver/zrleoutstream.c.i
.PHONY : libvncserver/zrleoutstream.i

# target to preprocess a source file
libvncserver/zrleoutstream.c.i:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/zrleoutstream.c.i
.PHONY : libvncserver/zrleoutstream.c.i

libvncserver/zrleoutstream.s: libvncserver/zrleoutstream.c.s
.PHONY : libvncserver/zrleoutstream.s

# target to generate assembly for a file
libvncserver/zrleoutstream.c.s:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/zrleoutstream.c.s
.PHONY : libvncserver/zrleoutstream.c.s

libvncserver/zrlepalettehelper.o: libvncserver/zrlepalettehelper.c.o
.PHONY : libvncserver/zrlepalettehelper.o

# target to build an object file
libvncserver/zrlepalettehelper.c.o:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/zrlepalettehelper.c.o
.PHONY : libvncserver/zrlepalettehelper.c.o

libvncserver/zrlepalettehelper.i: libvncserver/zrlepalettehelper.c.i
.PHONY : libvncserver/zrlepalettehelper.i

# target to preprocess a source file
libvncserver/zrlepalettehelper.c.i:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/zrlepalettehelper.c.i
.PHONY : libvncserver/zrlepalettehelper.c.i

libvncserver/zrlepalettehelper.s: libvncserver/zrlepalettehelper.c.s
.PHONY : libvncserver/zrlepalettehelper.s

# target to generate assembly for a file
libvncserver/zrlepalettehelper.c.s:
	$(MAKE) -f CMakeFiles/vncserver.dir/build.make CMakeFiles/vncserver.dir/libvncserver/zrlepalettehelper.c.s
.PHONY : libvncserver/zrlepalettehelper.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... client_examples_SDLvncviewer"
	@echo "... client_examples_backchannel"
	@echo "... client_examples_ppmtest"
	@echo "... edit_cache"
	@echo "... examples_backchannel"
	@echo "... examples_blooptest"
	@echo "... examples_camera"
	@echo "... examples_colourmaptest"
	@echo "... examples_example"
	@echo "... examples_filetransfer"
	@echo "... examples_fontsel"
	@echo "... examples_pnmshow"
	@echo "... examples_pnmshow24"
	@echo "... examples_regiontest"
	@echo "... examples_rotate"
	@echo "... examples_simple"
	@echo "... examples_simple15"
	@echo "... examples_storepasswd"
	@echo "... examples_vncev"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... vncclient"
	@echo "... vncserver"
	@echo "... client_examples/SDLvncviewer.o"
	@echo "... client_examples/SDLvncviewer.i"
	@echo "... client_examples/SDLvncviewer.s"
	@echo "... client_examples/backchannel.o"
	@echo "... client_examples/backchannel.i"
	@echo "... client_examples/backchannel.s"
	@echo "... client_examples/ppmtest.o"
	@echo "... client_examples/ppmtest.i"
	@echo "... client_examples/ppmtest.s"
	@echo "... client_examples/scrap.o"
	@echo "... client_examples/scrap.i"
	@echo "... client_examples/scrap.s"
	@echo "... common/d3des.o"
	@echo "... common/d3des.i"
	@echo "... common/d3des.s"
	@echo "... common/minilzo.o"
	@echo "... common/minilzo.i"
	@echo "... common/minilzo.s"
	@echo "... common/turbojpeg.o"
	@echo "... common/turbojpeg.i"
	@echo "... common/turbojpeg.s"
	@echo "... common/vncauth.o"
	@echo "... common/vncauth.i"
	@echo "... common/vncauth.s"
	@echo "... examples/backchannel.o"
	@echo "... examples/backchannel.i"
	@echo "... examples/backchannel.s"
	@echo "... examples/blooptest.o"
	@echo "... examples/blooptest.i"
	@echo "... examples/blooptest.s"
	@echo "... examples/camera.o"
	@echo "... examples/camera.i"
	@echo "... examples/camera.s"
	@echo "... examples/colourmaptest.o"
	@echo "... examples/colourmaptest.i"
	@echo "... examples/colourmaptest.s"
	@echo "... examples/example.o"
	@echo "... examples/example.i"
	@echo "... examples/example.s"
	@echo "... examples/filetransfer.o"
	@echo "... examples/filetransfer.i"
	@echo "... examples/filetransfer.s"
	@echo "... examples/fontsel.o"
	@echo "... examples/fontsel.i"
	@echo "... examples/fontsel.s"
	@echo "... examples/pnmshow.o"
	@echo "... examples/pnmshow.i"
	@echo "... examples/pnmshow.s"
	@echo "... examples/pnmshow24.o"
	@echo "... examples/pnmshow24.i"
	@echo "... examples/pnmshow24.s"
	@echo "... examples/regiontest.o"
	@echo "... examples/regiontest.i"
	@echo "... examples/regiontest.s"
	@echo "... examples/rotate.o"
	@echo "... examples/rotate.i"
	@echo "... examples/rotate.s"
	@echo "... examples/simple.o"
	@echo "... examples/simple.i"
	@echo "... examples/simple.s"
	@echo "... examples/simple15.o"
	@echo "... examples/simple15.i"
	@echo "... examples/simple15.s"
	@echo "... examples/storepasswd.o"
	@echo "... examples/storepasswd.i"
	@echo "... examples/storepasswd.s"
	@echo "... examples/vncev.o"
	@echo "... examples/vncev.i"
	@echo "... examples/vncev.s"
	@echo "... libvncclient/cursor.o"
	@echo "... libvncclient/cursor.i"
	@echo "... libvncclient/cursor.s"
	@echo "... libvncclient/listen.o"
	@echo "... libvncclient/listen.i"
	@echo "... libvncclient/listen.s"
	@echo "... libvncclient/rfbproto.o"
	@echo "... libvncclient/rfbproto.i"
	@echo "... libvncclient/rfbproto.s"
	@echo "... libvncclient/sockets.o"
	@echo "... libvncclient/sockets.i"
	@echo "... libvncclient/sockets.s"
	@echo "... libvncclient/tls_openssl.o"
	@echo "... libvncclient/tls_openssl.i"
	@echo "... libvncclient/tls_openssl.s"
	@echo "... libvncclient/vncviewer.o"
	@echo "... libvncclient/vncviewer.i"
	@echo "... libvncclient/vncviewer.s"
	@echo "... libvncserver/auth.o"
	@echo "... libvncserver/auth.i"
	@echo "... libvncserver/auth.s"
	@echo "... libvncserver/cargs.o"
	@echo "... libvncserver/cargs.i"
	@echo "... libvncserver/cargs.s"
	@echo "... libvncserver/corre.o"
	@echo "... libvncserver/corre.i"
	@echo "... libvncserver/corre.s"
	@echo "... libvncserver/cursor.o"
	@echo "... libvncserver/cursor.i"
	@echo "... libvncserver/cursor.s"
	@echo "... libvncserver/cutpaste.o"
	@echo "... libvncserver/cutpaste.i"
	@echo "... libvncserver/cutpaste.s"
	@echo "... libvncserver/draw.o"
	@echo "... libvncserver/draw.i"
	@echo "... libvncserver/draw.s"
	@echo "... libvncserver/font.o"
	@echo "... libvncserver/font.i"
	@echo "... libvncserver/font.s"
	@echo "... libvncserver/hextile.o"
	@echo "... libvncserver/hextile.i"
	@echo "... libvncserver/hextile.s"
	@echo "... libvncserver/httpd.o"
	@echo "... libvncserver/httpd.i"
	@echo "... libvncserver/httpd.s"
	@echo "... libvncserver/main.o"
	@echo "... libvncserver/main.i"
	@echo "... libvncserver/main.s"
	@echo "... libvncserver/rfbcrypto_openssl.o"
	@echo "... libvncserver/rfbcrypto_openssl.i"
	@echo "... libvncserver/rfbcrypto_openssl.s"
	@echo "... libvncserver/rfbregion.o"
	@echo "... libvncserver/rfbregion.i"
	@echo "... libvncserver/rfbregion.s"
	@echo "... libvncserver/rfbserver.o"
	@echo "... libvncserver/rfbserver.i"
	@echo "... libvncserver/rfbserver.s"
	@echo "... libvncserver/rfbssl_openssl.o"
	@echo "... libvncserver/rfbssl_openssl.i"
	@echo "... libvncserver/rfbssl_openssl.s"
	@echo "... libvncserver/rre.o"
	@echo "... libvncserver/rre.i"
	@echo "... libvncserver/rre.s"
	@echo "... libvncserver/scale.o"
	@echo "... libvncserver/scale.i"
	@echo "... libvncserver/scale.s"
	@echo "... libvncserver/selbox.o"
	@echo "... libvncserver/selbox.i"
	@echo "... libvncserver/selbox.s"
	@echo "... libvncserver/sockets.o"
	@echo "... libvncserver/sockets.i"
	@echo "... libvncserver/sockets.s"
	@echo "... libvncserver/stats.o"
	@echo "... libvncserver/stats.i"
	@echo "... libvncserver/stats.s"
	@echo "... libvncserver/tight.o"
	@echo "... libvncserver/tight.i"
	@echo "... libvncserver/tight.s"
	@echo "... libvncserver/tightvnc-filetransfer/filelistinfo.o"
	@echo "... libvncserver/tightvnc-filetransfer/filelistinfo.i"
	@echo "... libvncserver/tightvnc-filetransfer/filelistinfo.s"
	@echo "... libvncserver/tightvnc-filetransfer/filetransfermsg.o"
	@echo "... libvncserver/tightvnc-filetransfer/filetransfermsg.i"
	@echo "... libvncserver/tightvnc-filetransfer/filetransfermsg.s"
	@echo "... libvncserver/tightvnc-filetransfer/handlefiletransferrequest.o"
	@echo "... libvncserver/tightvnc-filetransfer/handlefiletransferrequest.i"
	@echo "... libvncserver/tightvnc-filetransfer/handlefiletransferrequest.s"
	@echo "... libvncserver/tightvnc-filetransfer/rfbtightserver.o"
	@echo "... libvncserver/tightvnc-filetransfer/rfbtightserver.i"
	@echo "... libvncserver/tightvnc-filetransfer/rfbtightserver.s"
	@echo "... libvncserver/translate.o"
	@echo "... libvncserver/translate.i"
	@echo "... libvncserver/translate.s"
	@echo "... libvncserver/ultra.o"
	@echo "... libvncserver/ultra.i"
	@echo "... libvncserver/ultra.s"
	@echo "... libvncserver/websockets.o"
	@echo "... libvncserver/websockets.i"
	@echo "... libvncserver/websockets.s"
	@echo "... libvncserver/zlib.o"
	@echo "... libvncserver/zlib.i"
	@echo "... libvncserver/zlib.s"
	@echo "... libvncserver/zrle.o"
	@echo "... libvncserver/zrle.i"
	@echo "... libvncserver/zrle.s"
	@echo "... libvncserver/zrleoutstream.o"
	@echo "... libvncserver/zrleoutstream.i"
	@echo "... libvncserver/zrleoutstream.s"
	@echo "... libvncserver/zrlepalettehelper.o"
	@echo "... libvncserver/zrlepalettehelper.i"
	@echo "... libvncserver/zrlepalettehelper.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

